global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'user-service'
    static_configs:
      - targets: ['user-service:8000']

  - job_name: 'event-analytics-service'
    static_configs:
      - targets: ['event-analytics-service:8001']

  - job_name: 'ai-inference-service'
    static_configs:
      - targets: ['ai-inference-service:8002']

  - job_name: 'communication-service'
    static_configs:
      - targets: ['communication-service:8003']

  - job_name: 'api-gateway'
    static_configs:
      - targets: ['api-gateway:8004']